### ISSUE TITLE
Fixed progress bar and apparently infinite loop on land cover change

### ISSUE THREAD

**Issue by mone27** [semiautomaticgit/SemiAutomaticClassificationManual#16]
Hi,
I have started a land cover change procedure on two raster produced using saga and the progress bar is stuck on 20 %, while on the logs there are messages like that (the value started from 0 and is increasing by step of 1):
`2018-11-28T16:48:39     INFO    Executing : Please wait ...
2018-11-28T16:48:41     INFO    Executing : (0/1) value 2289`
It is running since a couple of hour on a quite small area (10km x 10km) and I don't if it will ever finish, however the progress stuck is surely a bug.
I am using Qgis 3.4 on Fedora 29.
I apologise for giving such a small amount of information but I don't know what can be useful to correct the issue, please tell me what is needed for a proper bug report.
I have tried to quick look at the source code but found nothing useful

**Comment by semiautomaticgit** [comment]
Hi, please follow these steps to copy the whole SCP log file 
https://semiautomaticclassificationmanual.readthedocs.io/en/latest/faq.html#how-can-i-report-an-error
Thank you
